# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
    push:
        branches: ["main"] # Fontos, hogy melyik branch van beállítva.
    pull_request:
        branches: ["main"] # Fontos, hogy melyik branch van beállítva.

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Github repod -> Settings -> Acions -> General -> Allow all actions and reusable workflows; Read and write permissions; Mindkét helyen nyomj ár a mentésre. -> A badge-ekhez kell.
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21 # Java verzió egyezzen azzal, amit projektben használtál. Csekk: Terminálban: java -version
              uses: actions/setup-java@v4
              with:
                  java-version: "21" # Java verzió egyezzen azzal, amit projektben használtál. Csekk: Terminálban: java -version
                  distribution: "temurin"
                  cache: maven

            - name: Build and Test with Maven
              run: mvn -B clean test

              # Ez a rész generálja a plecsnit a README-be a tesztfutás után!
            - name: Generate JaCoCo Badge
              id: jacoco
              uses: cicirello/jacoco-badge-generator@v2
              with:
                  generate-branches-badge: true
                  jacoco-csv-file: target/site/jacoco/jacoco.csv
            # Ez a rész pedig visszatölti a képet a GitHubra, hogy be tudd illeszteni
            - name: Commit and push the badge
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .github/badges/*.svg
                  git commit -m "Updated coverage badge" || exit 0
                  git push
